eureka:
  instance:
    hostname: localhost

  #是否注册到eureka
  client:
    registerWithEureka: false
  #是否从eureka中拉取注册信息
    fetchRegistry: false
  ##暴露eureka服务的地址
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

  #自我保护模式，当出现出现网络分区、eureka在短时间内丢失过多客户端时，会进入自我保护模式，即一个服务长时间没有发送心跳，eureka也不会将其删除，默认为true
  server:
    enable-self-preservation: true
